[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
backgroundColor = "#F0F1DF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D2638"
font = "sans serif"

[client]
showSidebarNavigation = false

[runner]
fastReruns = true
