[theme]
base = "light"
primaryColor = "#313A55"
backgroundColor = "#F0F1DF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D2638"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
